[build]
  publish = "."
  ignore = "/bin/false"

[functions]
  directory = "netlify/functions"

# Block the GH Actions sync source folder from public access
[[redirects]]
  from = "/sync/*"
  to = "/"
  status = 404
